http:
  port: 8080
admin:
  port: 9876
  host: localhost
# ---------------------------------------------------------------------------------------
# api endpoints
apiEndpoints:
  accommodations:
    host: localhost
    paths: "/accommodations/*"
  amenities:
    host: localhost
    paths: "/amenities/*"
  accommodationTypes:
    host: localhost
    paths: "/accommodation-types/*"
  activityTypes:
    host: localhost
    paths: "/activity-types/*"
  activities:
    host: localhost
    paths: "/activities/*"
  attractionTypes:
    host: localhost
    paths: "/attraction-types/*"
  attractions:
    host: localhost
    paths: "/attractions/*"
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
# ---------------------------------------------------------------------------------------
# service endpoints
serviceEndpoints:
  accommodationsService:
    url: "http://accommodation-service:3000"
  activitiesService:
    url: "http://activity-service:3000"
  attractionsService:
    url: "http://attraction-service:3000"
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
# ---------------------------------------------------------------------------------------
# pipelines
pipelines:
  default:
    apiEndpoints:
      - accommodations
      - amenities
      - accommodationTypes
      - activityTypes
      - activities
      - attractionTypes
      - attractions
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "GET, POST, PATCH, DELETE, OPTIONS"
      - log:
          - action:
              message: "${req.method} request to ${req.url}"
              level: info
  accommodationsPipeline:
    apiEndpoints:
      - accommodations
      - amenities
      - accommodationTypes
    policies:
      - log:
          - action:
              message: "Accommodations Pipeline - ${req.method} request to ${req.url}"
              level: info
      - proxy:
          - action:
              serviceEndpoint: accommodationsService
              changeOrigin: true
  activitiesPipeline:
    apiEndpoints:
      - activityTypes
      - activities
    policies:
      - log:
          - action:
              message: "Activities Pipeline - ${req.method} request to ${req.url}"
              level: info
      - proxy:
          - action:
              serviceEndpoint: activitiesService
              changeOrigin: true
  attractionsPipeline:
    apiEndpoints:
      - attractionTypes
      - attractions
    policies:
      - log:
          - action:
              message: "Attractions Pipeline - ${req.method} request to ${req.url}"
              level: info
      - proxy:
          - action:
              serviceEndpoint: attractionsService
              changeOrigin: true
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
