http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  accommodations:
    host: localhost
    paths: "/accommodations/*"
  amenities:
    host: localhost
    paths: "/amenities/*"
  accommodationTypes:
    host: localhost
    paths: "/accommodation-types/*"
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
serviceEndpoints:
  accommodationsService:
    url: "http://accommodation-service:3000"
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - accommodations
      - amenities
      - accommodationTypes
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "GET, POST, PATCH, DELETE, OPTIONS"
      - log:
          - action:
              message: "${req.method} request to ${req.url}"
              level: info
  accommodationsPipeline:
    apiEndpoints:
      - accommodations
      - amenities
      - accommodationTypes
    policies:
      - log:
          - action:
              message: "Accommodations Pipeline - ${req.method} request to ${req.url}"
              level: info
      - proxy:
          - action:
              serviceEndpoint: accommodationsService
              changeOrigin: true
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
